# Generated by Django 5.2.11 on 2026-06-13 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_industry_alter_company_name_and_more'),
        ('projects', '0003_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='projects_pr_categor_2f76f8_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['region', 'status'], name='projects_pr_region_e37de3_idx'),
        ),
    ]
