# Generated by Django 5.2.11 on 2026-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_category_alter_project_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], db_index=True, default='open', max_length=20),
        ),
    ]
