# Generated by Django 5.2.11 on 2026-06-13 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('COMPANY_CREATED', 'Company creation'), ('PROJECT_CREATED', 'Project creation'), ('INVESTMENT_CREATED', 'Investment creation')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['created_at'], name='core_contac_created_63cb1b_idx'),
        ),
    ]
