# Generated by Django 5.2.11 on 2026-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_action_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Tizimga kirish'), ('COMPANY_CREATED', 'Korxona yaratildi'), ('PROJECT_CREATED', 'Loyiha yaratildi'), ('INVESTMENT_CREATED', 'Investitsiya yaratildi')], db_index=True, max_length=40),
        ),
    ]
