# Generated by Django 5.2.11 on 2026-06-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=120)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_period_months', models.IntegerField()),
                ('region', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('risks', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InvestorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='investments.investment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
