# Generated by Django 5.2.11 on 2026-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_industry_alter_company_name_and_more'),
        ('investments', '0002_seed_investments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='region',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sector',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['sector', 'status'], name='investments_sector_7dad7f_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['region', 'status'], name='investments_region_a38c8f_idx'),
        ),
    ]
