# Generated by Django 5.2.11 on 2026-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_region_alter_investment_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('funded', 'Moliyalashtirilgan'), ('closed', 'Yopilgan')], db_index=True, default='open', max_length=20),
        ),
    ]
