# Generated by Django 5.2.11 on 2026-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_existing_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COMPANY', 'Korxona'), ('INVESTOR', 'Investor')], default='INVESTOR', max_length=20),
        ),
    ]
