# Generated by Django 5.2.11 on 2026-06-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_industry_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Korxona', 'verbose_name_plural': 'Korxonalar'},
        ),
    ]
